interledgerjs/five-bells-ledger

migrations/20150820161813-init.js
npm-shrinkwrap.json
package.json
src/controllers/transfers.js
src/lib/accountBalances.js
src/lib/transferExpiryMonitor.js
src/models/account.js
src/models/entry-group.js
src/models/entry.js
test/accountSpec.js

Requires https://github.com/interledger/five-bells-shared/pull/35.
Also: https://github.com/interledger/passport-http-signature will need to be published for this to work.
Once it is, npm-shrinkwrap will need to be updated.

[FEATURE] Entry/EntryGroup

---

npm-shrinkwrap.json
package.json
src/lib/notificationWorker.js
src/models/notification.js
test/subscriptionSpec.js

Depends on https://github.com/interledger/five-bells-shared/pull/40.

[FEATURE] Retry notifications

---

app.js
src/controllers/accounts.js
test/accountSpec.js
test/putTransferSpec.js

[FEATURE] Require auth for GET /accounts/*

---

circle.yml

See: https://discuss.circleci.com/t/unable-to-use-docker-cp-but-it-worked-2-days-ago/1137/7

Fix CircleCI docker cp bug

---

README.md
circle.yml
package.json
src/lib/notificationWorker.js
src/services/config.js
test/accountSpec.js
test/helpers/db.js
test/subscriptionSpec.js

Closes #64.
Run test suite against MySQL, Postgres and SQLite.

Test against three databases

---

app.js
migrations/20150820161813-init.js
migrations/20160107075645-identity-to-connector.js
package.json
scripts/create_user.js
src/controllers/accounts.js
src/controllers/transfers.js
src/models/account.js
test/accountSpec.js
test/data/accounts.json
test/transferStateSpec.js

* Add unauthenticated `/connectors` endpoint.
* `/state`: sign nonexistent transfers; allow specification of `signatureType` and state.
* Requires https://github.com/interledger/five-bells-shared/pull/42

[FEATURE] /connectors and always 200 for transfer state

---

README.md

Update README to set env variables when using sqlite in memory

---

migrations/20160107082953-additional-info.js
npm-shrinkwrap.json
package.json
src/models/transfer.js

Requires https://github.com/interledger/five-bells-shared/pull/44

[FEATURE] part_of_payment -> additional_info

---

app.js
npm-shrinkwrap.json
package.json
src/controllers/accounts.js
src/models/account.js
test/accountSpec.js
test/putTransferSpec.js

Fixes #105 
Depends on https://github.com/interledger/five-bells-shared/pull/45

[FEATURE] Allow account+ledger lookup without auth

---

README.md
src/services/auth.js
src/services/config.js

[FEATURE] LEDGER_AUTH_{BASIC,HTTP_SIGNATURE}_ENABLED

---

migrations/20150820161813-init.js
src/controllers/subscriptions.js
test/subscriptionSpec.js

@justmoon been hacking on the repo to get up to speed ... I'd like to resolve #70 with this PR. Let me know if it looks ok.

Prevent duplicate subscriptions

---

src/services/config.js

Requires https://github.com/interledger/five-bells-shared/pull/46

[TASK] Use Config.castBool

---

src/controllers/subscriptions.js

This is necessary to fix the visualization. /cc @MatthewPhinney

[FIX] allow admin to subscribe to any account

---

npm-shrinkwrap.json
package.json
src/lib/seed-db.js
src/models/accounts.js
src/models/db/account.js
src/services/auth.js
test/accountSpec.js
test/data/accounts.json

Depends on https://github.com/interledger/five-bells-shared/pull/51

Store hashed passwords in database

---

npm-shrinkwrap.json
package.json
src/lib/seed-db.js

Depends on https://github.com/interledger/five-bells-shared/pull/55

[TASK] five-bells-shared/hashPassword

---

src/models/transfers.js

The static verification is done by the JSON schema validator, which is invoked by the "createBodyParser" middleware.
The execution condition fulfillment is checked by `hasValidFulfillment` in `processStateTransitions`.
Is there anything else that should be done?

Remove obsolete comments

---

npm-shrinkwrap.json
package.json
src/lib/app.js
src/lib/seed-db.js
src/models/accounts.js
src/models/transfers.js
src/services/auth.js
src/services/config.js
src/services/db.js
src/services/uriManager.js
test/transferStateSpec.js

Update to use new config
https://github.com/interledger/five-bells-shared/pull/63/

Update config module

---

src/lib/transferExpiryMonitor.js
src/models/db/transfer.js
src/models/transfers.js
test/fulfillmentSpec.js
test/getTransferSpec.js

See the corresponding PR in shared: https://github.com/interledger/five-bells-shared/pull/76.
This has been tested with the ilp-server to ensure nothing is broken.

Add rejection_reason to transfers

---

.eslintignore
.gitignore
circle.yml
package.json

Requires interledger/five-bells-integration-test#3

[TEST] Run integration test module.

---

npm-shrinkwrap.json
package.json
src/controllers/transfers.js
src/models/transfers.js
test/transferStateSpec.js

This will fail until https://github.com/interledger/five-bells-shared/pull/88 is merged.

Add schema validation to transfer state receipt tests

---

src/lib/app.js
src/lib/config.js
src/lib/notificationUtils.js
src/lib/notificationWorker.js
src/services/config.js
src/services/notificationWorker.js

~~Depends on https://github.com/interledger/five-bells-ledger/pull/166~~

Allow TLS client auth for subscription notifications

---

src/lib/config.js
src/lib/seed-db.js

To allow admin account to authenticate using client certificate

Default admin account created with TLS certificate fingerprint

---

src/controllers/metadata.js
src/lib/app.js
src/lib/config.js
test/metadataSpec.js

Return metadata from `/`, which includes the ledger's `public_key` among other things.
/cc @justmoon

[FEATURE] metadata endpoint: /

---

npm-shrinkwrap.json
package.json

Requires interledger/five-bells-shared#100

Add `npm run bump` to automate version bumping

---

npm-shrinkwrap.json
package.json

Includes fix for Account schema

Update five-bells-shared to 11.2.1

---

src/lib/timerWorker.js
src/lib/transferExpiryMonitor.js
src/models/transfers.js
test/accountSpec.js
test/fulfillmentSpec.js
test/getTransferSpec.js
test/healthSpec.js
test/metadataSpec.js
test/notificationSpec.js
test/putTransferSpec.js
test/subscriptionSpec.js
test/timeQueueSpec.js
test/timerWorkerSpec.js
test/transferStateSpec.js

Spacing after * in generator functions

Fix lint errors

---

npm-shrinkwrap.json
package.json
src/lib/app.js
src/lib/seed-db.js

Includes two minor changes for a breaking change
https://github.com/interledger/five-bells-shared/commit/9d32aadb4fb9e5affca688efeeda0724fbd66479

Update five-bells-shared to 12.0.0

---

README.md
src/lib/config.js
src/models/transfers.js
test/putTransferSpec.js

Fixes https://github.com/interledger/five-bells-ledger/issues/173
It is disabled by default, so this is not a breaking change.

[FEATURE] credit auth

---

circle.yml
scripts/ci-deploy.sh
scripts/ci-test.sh

CircleCI deploy task currently broken due to parallelization changes
See: https://circleci.com/gh/interledger/five-bells-ledger/850

CI: Move deploy into script, fix error due to parallelizing builds

---

README.md
src/controllers/metadata.js
src/lib/accountBalances.js
src/lib/config.js
src/models/transfers.js
test/configSpec.js
test/metadataSpec.js
test/putTransferSpec.js

Scale and precision configurable
`LEDGER_AMOUNT_SCALE`
`LEDGER_AMOUNT_PRECISION`
Throw exception if amount precision > 15 when using oracledb
Exposed via metadata endpoint

Feature: ledger precision is configurable and enforced on transfer amounts

---

scripts/ci-deploy.sh

Will migrate to using Github pages
See:
https://github.com/interledger/five-bells-condition/blob/master/scripts/publish_spec.sh

Disable uploading apidocs for now

---

src/lib/config.js
src/lib/notificationWorker.js
src/models/accounts.js
src/models/transfers.js

When clearing the cache on CircleCI, eslint-config-standard must have gotten updated and a new rule added. Because of that we have some test failures right now.

Fix some new eslint issues

---

package.json
src/controllers/accounts.js
src/lib/app.js
src/lib/notificationWorker.js
src/models/accounts.js
test/accountSpec.js
test/data/transfers/simpleWithExpiry.json
test/helpers/app.js
test/helpers/timing.js

Adds a new /accounts/:name/transfers endpoint which provides transfer notifications via the websocket protocol.

Provide notifications via websockets

---

scripts/generate_keys.js

Simple utility script to generate Ed25519 keypair.

Add key generator script

---

README.md
package.json
scripts/json-schema-to-markdown-table2.js
src/controllers/metadata.js
src/lib/app.js
src/lib/config.js
test/configSpec.js
test/metadataSpec.js

Addresses https://github.com/interledger/five-bells-ledger/issues/308, and required in order to address https://github.com/interledger/js-ilp-plugin-bells/issues/21

feat: add config option for ILP prefix

---

package.json
src/errors/fulfillment-not-found-error.js
src/errors/transfer-not-found-error.js
src/lib/notificationBroadcasterWebsocket.js
src/models/db/fulfillments.js
src/models/transfers.js
test/fulfillmentSpec.js

Related to https://github.com/interledger/js-ilp-plugin-bells/pull/29 and https://github.com/interledger/rfcs/pull/84#issuecomment-242001174

feat: getFulfillment {Transfer,Fulfillment}NotFoundError

---

scripts/apidoc_intro.md.ejs
src/lib/config.js
test/configSpec.js
test/metadataSpec.js

resolves https://github.com/interledger/five-bells-ledger/issues/317

Docs: document LEDGER_ILP_PREFIX field

---

scripts/apidoc_intro.md.ejs
src/controllers/accounts.js
src/controllers/metadata.js
src/lib/app.js
src/lib/config.js
src/models/accounts.js
test/accountSpec.js
test/configSpec.js
test/metadataSpec.js

feat: BREAKING remove /connectors; send them as metadata

---

package.json
src/controllers/accounts.js
src/errors/missing-fulfillment-error.js
src/models/db/fulfillments.js
src/models/transfers.js
test/fulfillmentSpec.js
test/putTransferSpec.js

Depends on https://github.com/interledger/five-bells-shared/pull/156

feat: send ledger-plugin RFC errors

---

src/controllers/metadata.js
test/metadataSpec.js

remove subscriptions, add websocket notifications and transfer rejection
resolves https://github.com/interledger/five-bells-ledger/issues/326

fix: update metadata

---

circle.yml
package.json
src/lib/notificationBroadcasterWebsocket.js
test/notificationSpec.js

fix: /accounts/*/transfers should include messages

---

package.json
src/models/messages.js
test/data/messages/fromto.json
test/postMessageSpec.js

Fixes #346
Depends on https://github.com/interledgerjs/five-bells-shared/pull/160

feat: allow admin to send message as any user

---

package.json
src/models/messages.js
test/postMessageSpec.js

Depends on https://github.com/interledgerjs/five-bells-shared/pull/161
Fixes https://github.com/interledgerjs/five-bells-ledger/issues/349

feat: include from/to in message notifications

---

src/controllers/accounts.js
test/accountSpec.js

Fixes https://github.com/interledgerjs/five-bells-ledger/issues/363

fix: verify account id before create/update

---

src/controllers/_apidoc.js
src/controllers/messages.js
src/errors/no-subscriptions-error.js
src/lib/app.js
src/lib/notificationBroadcasterWebsocket.js
src/models/accounts.js
src/models/messages.js
test/postMessageSpec.js

* Warn on startup if a recommended connector doesn't exist.
* Return a `NoSubscriptionsError` error on `POST /messages` if the receiving account has no active websockets.
Fixes https://github.com/interledgerjs/five-bells-ledger/issues/362

feat: NoSubscriptionsError, verify connectors

---

docs/apidoc_intro.ejs.md
src/controllers/messages.js

Fixes https://github.com/interledgerjs/five-bells-ledger/issues/367

docs: fix Send Message docs

---

README.md
package.json
src/models/db/fulfillments.js
src/models/db/utils.js
src/models/transfers.js
test/fulfillmentSpec.js

See the discussion in https://github.com/interledger/five-bells-ledger/issues/330.

refactor: improve ledger performance. fixes #330

---

scripts/ci-test.sh
src/lib/notificationBroadcasterWebsocket.js
test/notificationSpec.js

fix: dedupe notifications when sender and receiver are same

---

docs/apidoc_intro.ejs.md
src/lib/config.js
src/lib/rpcHandler.js
src/services/makeRpcHandler.js
test/notificationSpec.js

Fixes https://github.com/interledgerjs/five-bells-ledger/issues/382

feat: intermittently ping websocket

---

package.json
scripts/build_docs.js

Fixes https://github.com/interledgerjs/five-bells-ledger/issues/392

fix: five-bells-shared@21.0.2

---

package.json
src/controllers/transfers.js
src/lib/app.js
src/lib/rpcHandler.js
src/models/db/adjustments.js
src/models/transfers.js
test/putTransferSpec.js
test/rejectionSpec.js

Depends on https://github.com/interledgerjs/five-bells-integration-test/pull/63, https://github.com/interledgerjs/five-bells-shared/pull/179

feat: BREAKING Use RejectionMessage for ILP Errors

---

src/lib/seed-db.js
test/accountSpec.js

- fixes setup of the admin account if postgres is used
- adds a unit test to check if the admin account was correctly setup

fix: fixes admin account setup

---

src/lib/transferExpiryMonitor.js
src/lib/updateState.js
src/models/transfers.js

fix: avoids that executed_at is after expires_at

---

package.json

Depends on: five-bells-shared#dj-ilqp

fix: Support new message format

---

src/controllers/authTokens.js
src/lib/config.js
src/models/authTokens.js
test/getAuthTokenSpec.js

Related to https://github.com/interledgerjs/ilp-plugin-bells/pull/136#issuecomment-307850559

feat: add token_max_age to /auth_token

---

package.json

For https://github.com/interledgerjs/ilp-plugin-bells/pull/142

chore: five-bells-shared@25.1.1

---

package-lock.json
package.json
src/lib/koa-websocket.js

fixes a vulnerability in ws prior to v3.3.1 https://snyk.io/vuln/npm:ws:20171108

fix: update ws

---

package-lock.json
package.json

dependency was vulnerable to https://snyk.io/vuln/npm:hoek:20180212

chore: bump dependency version

---

package-lock.json
package.json

fixes vulnerability https://snyk.io/vuln/npm:braces:20180219?utm_campaign=vuln_alert&utm_medium=email&utm_source=Vuln

chore: bump knex
