interledgerjs/five-bells-ledger

migrations/20150820161813-init.js
src/controllers/transfers.js
src/lib/transferExpiryMonitor.js
src/models/transfer.js
test/putTransferSpec.js

Allow clients to reject transfers, and require the `execution_condition_fulfillment` to do so.
Requires https://github.com/interledger/five-bells-shared/pull/37

[FEATURE] Require fulfillment to reject transfer

---

test/putTransferSpec.js

Our code tries to send out the notification immediately. If it's fast it'll succeed in doing so before the nock handler is registered. So @sentientwaffle's fix is the correct one.

Fix the bizarre intermittent nock failure

---

README.md
app.js
src/lib/accountBalances.js
src/models/account.js
src/services/config.js
test/accountSpec.js
test/data/accounts.json

* Fixes #57 (docs), #58 (default admin username), #59 (auto-update admin password)
* Correctly use "hold" account transactions so that postgres behaves as expected.
* Move "hold" account creation to `app.js` (@justmoon if this should be in the migration instead, let me know).

[TASK] Assorted admin/hold fixes

---

src/controllers/_apidoc.js
src/controllers/subscriptions.js
src/lib/app.js
test/subscriptionSpec.js

Preliminary auth for subscription endpoints. The logic is as follows:
**GET**: a user may only view a subscription for an account they own, unless they are an admin, in which case they can view any subscription. They will receive a 404 if the subscription doesn't exist and a 403 if they are not authorized.
**PUT**: a user may only create a subscription in which the "owner" matches the user.
**What restrictions are placed on the `target` account(s)?**
**DELETE**: a user may only delete a subscription if they are the owner. An admin may delete any subscription. *Should we allow this?*
Once the above questions are addressed, this will resolve #99.

Subscription auth

---

package.json

Recently merged refactor depends on `five-bells-shared@8.9.0`, otherwise throws:
```
2016-01-23T02:06:00.613Z app CRIT TypeError: this.db.init is not a function
at App._start (/var/app/src/lib/app.js:58:19)
at next (native)
at onFulfilled (/var/app/node_modules/co/index.js:65:19)
at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:11:23)
at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:488:31)
at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:545:18)
at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:590:10)
at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:673:18)
at Async._drainQueue (/var/app/node_modules/bluebird/js/release/async.js:125:16) …
```

Refactor depends on five-bells-shared@8.9.0

---

package.json
src/controllers/transfers.js
test/transferStateSpec.js

Fixes #89 (though I call the parameter `condition_state` instead of `pretend_state` to make it more clear what the intended purpose is).
When `condition_state` is provided, the `/state` endpoint will return `condition_state` and `condition_digest`, in addition to the regular `digest` &c.

[FEATURE] /state: type=sha256, condition_state

---

src/models/accounts.js
src/models/db/accounts.js

Moves lower-level database access from the models to a database abstraction layer so that the business logic in the model is easier to read.

Extract database code from accounts model

---

src/models/db/accounts.js
src/models/db/subscriptions.js
src/models/db/transfers.js
src/models/subscriptions.js
src/models/transfers.js

This completes the method extraction for the models in this repo.
Remaining work in this refactoring:
1. Use POJOs in interface between db methods and models
2. Use db methods in "lib"

Split database layer from subscriptions and transfers models

---

npm-shrinkwrap.json
package.json
src/lib/app.js
src/models/db/account.js
src/services/auth.js
src/services/config.js

Server-side Client Certificate Authentication
Uses https://github.com/ripple/passport-client-certificate
Working example:
Server
```diff
_makeRouter () {
const router = new Router()
-    router.get('/health', health.getResource)
+
+    router.get('/health',
+        passport.authenticate(['client-cert']),
+        health.getResource)
```
Client
```js
var fs = require('fs');
var https = require('https');
var options = {
hostname: 'localhost',
port: 3000,
path: '/health',
method: 'GET',
key: fs.readFileSync('client1-key.pem'),
cert: fs.readFileSync('client1-crt.pem'),
ca: fs.readFileSync('ca-crt.pem') // Trust the test servers self-signed cert
};
var req = https.request(options, function(res) {
res.on('data', function(data) {
process.stdout.write(data);
});
});
req.end();
```
```shell
$ …
```

Server-side Client Certificate Authentication

---

test/getTransferSpec.js
test/putTransferSpec.js

This should not be merged until #158 is merged. I need to use the newer version of five-bell-shared, so that I can validate the notifications.
There is a lot of duplicated code between the tests. Once I have added schema validation to each test, I'll consolidate, probably by adding a file with some helper methods, so we don't need the validators in each test file. I'm submitting PRs one by one, so they are easier to review.

Validate transfer schemas

---

package.json
src/lib/accountBalances.js
test/putTransferSpec.js

Uses bignumber.js
```js
> 94.9899 - 5.0101
89.97980000000001
```
vs.
```js
> (new Bignumber(94.9899)).minus(5.0101).toNumber()
89.9798
```
Keep numbers as strings

FIX: Floating point precision errors when applying debits/credits

---

src/models/db/account.js
src/models/db/entry.js
test/accountSpec.js
test/data/transfers/fromZeroMinBalance.json
test/putTransferSpec.js

Before this fix, if you PUT an account that just contains a password change it will zero the account's balance.
This was discovered while attempting to solve RILP-354, which was not reproducible.

Fix overwriting of account settings when not specified in PUT

---

circle.yml

The coveralls task expects the sqlite tests to run
Error message:
```
docker run --volumes-from ledger-test-sqlite -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} interledger/five-bells-ledger npm run coveralls
Error response from daemon: no such id: ledger-test-sqlite
Action failed: docker run --volumes-from ledger-test-sqlite -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} interledger/five-bells-ledger npm run coveralls
docker run --volumes-from ledger-test-sqlite -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} interledger/five-bells-ledger npm run coveralls returned exit code 1
Error response from daemon: no such id: ledger-test-sqlite Action failed: docker run --volumes-from ledger-test-sqlite -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} interledger/five-bells-ledger npm run …
```

CI: Fix npm run coveralls

---

src/models/db/account.js
test/accountSpec.js

Bug:
```js
PUT http://localhost:3001/accounts/Skyla
{"name":"Skyla","balance":"50","is_admin":false}
```
Returns
```js
{"id":"InvalidBodyError","message":"Account name must match the one in
the URL (strictEqual, expected: \"skyla\", actual: \"Skyla\")"}
```

FIX: Lowercase name and id when creating accounts

---

test/accountSpec.js
test/fulfillmentSpec.js
test/getTransferSpec.js
test/helpers/db.js
test/notificationSpec.js
test/putTransferSpec.js
test/subscriptionSpec.js
test/transferStateSpec.js

Should reduce unit test time significantly

Truncate tables between tests cases. Only migrate once

---

scripts/ci-deploy.sh

The deploy task only runs on container(0) when builds are parallelized.
Artifacts generatd in other containers during test are not available.
CircleCI Support:
> Container 0 is the only one used for deployment, however prior to the
> deployment taking place all of the generated artifacts are already
> uploaded to S3 so if you need to use them you can pull them down or
> reference them from S3.

CI: Fix apidoc upload

---

scripts/ci-test.sh

Deploy runs on the VM 0 in a parallelized build. If the docker image is
not there, build it first.
See failing build: https://circleci.com/gh/interledger/five-bells-ledger/897

CI: Fix missing docker image on deploy task

---

test/accountSpec.js

Covers case in RILP-349. It looks like the bug was already fixed.

Add unit test for creating account without password or fingerprint

---

src/lib/notificationWorker.js

JSON.stringify the response body
```
2016-03-28T22:51:50.699Z notificationWorker DEBUG remote error for notification 502 { id: 'ExternalError',
message: 'Remote error: status=400 body=[object Object]' }
```

Fix debug message

---

src/lib/config.js

From this:
```
> five-bells-ledger@11.0.0 start /Users/alan/Projects/five-bells-ledger
> node src/app.js
/Users/alan/Projects/five-bells-ledger/src/lib/config.js:96
const isOracle = config.getIn(['db', 'uri']).startsWith('oracle://') !== null
^
TypeError: Cannot read property 'startsWith' of undefined
```
To correct error message:
```
Error: Must set LEDGER_DB_URI or LEDGER_UNIT_DB_URI
at getKnexConfig (/Users/alan/Projects/five-bells-ledger/src/lib/knex.js:43:11)
```

Fix: Config error messaging when missing DB_URI

---

package.json
scripts/bench_password_hash.js
src/lib/seed-db.js
src/migrations/201602231400_initial.js
src/models/accounts.js
src/models/db/account.js
src/services/auth.js
test/helpers/db.js

Requires interledger/five-bells-shared#136
Removes password hashing from five-bells-ledger and uses the facility in five-bells-shared.
Makes password hashing asynchronous. Each password hashing iteration with 10 rounds of bcrypt takes around 60ms in my tests. This is for every request to the ledger and on the main thread. With this patch, the password hashing becomes asynchronous and is removed from the main thread. This reduces the total duration of the unit tests from 35s to about 8s on my machine. The number of "prepare transfer" requests per second increases from 60 req/s to about 110 req/s.
Note that the unit tests were using some rudimentary partial caching for password hashes, so the impact on a live system could be even larger, depending on the number of cores available.
This …

Switch to PBKDF2

---

src/migrations/201602231400_initial.js

This change, 256758d, introduced a change in the scale (digits after
decimal place). To support amounts greater than 1,000,000 (6 digits) we
need more than 10 digits of precision (6 digits before + 4 digits after
decimal point).

fix: db precision is too low if funding accounts > 1,000,000 balance

---

package.json

ws@v1.0.1 fixed a DoS vulnerability due to buffer allocation https://github.com/websockets/ws/releases/tag/1.0.1

Update ws dependency to address DoS vulnerability

---

src/lib/db.js

The ledger would throw an exception with
```
LEDGER_SYNC_TRUE=1
LEDGER_DB_URI=postgres://localhost/wallet1-ledger
```

fix: handle no username DB_URI

---

README.md
docs/apidoc_intro.ejs.md
src/lib/app.js

If the database has already been created, then the `create.sql` script run by `createTables` will throw an error without doing anything. This removes the need to run the first time with `LEDGER_DB_SYNC=1`, and run subsequent times with it unset.

Feat: eliminate LEDGER_DB_SYNC

---

package.json

Currently, we have to bump the version of integration tests on every module, every time we change them. We also often get into deadlocks we have to resolve by skipping tests.
This is part of a series of pull requests to switch to five-bells-integration-test-loader, which will solve both problems by loading the integration tests according to the same rules as other modules: Use latest master, unless there is a branch of the same name, then use that branch.
It's probably easiest to understand by looking at the following two links:
* b241d14768b02a42a34dc42e91d5101db7de0525
* https://github.com/interledgerjs/five-bells-integration-test-loader

Use integration test loader

---

src/models/transfers.js
test/fulfillmentSpec.js

Before fulfilling a transfer, the ledger did not check if the transfer was expired. This has several
securtiy-critical consequences, e.g.: An attacker can bring a connector to put funds on hold and
trick the ledger to fulfill the hold after it is expired. In this scenario, the connector can not
pass on the fulfillment in time to the source ledger and, thus, losses the funds.

fix: Check expiry date before fulfilling a transfer

---

src/lib/notificationBroadcasterWebsocket.js
src/lib/rpcHandler.js
test/notificationSpec.js

As the title says, fixes #385.
The implementation works by replacing EventEmitter with a custom dispatcher using JavaScript's built-in Map/Set primitives.
Add basic tests for admin (3rd party) subscriptions and a regression test for #385.

Only send one notification, even if two subscribed accounts are involved in a transfer

---

package.json
src/lib/db.js

* Don't use `logger` for websocket connections, it tries to attach events to `this.res`, which doesn't exist.
* More detailed logging when pg-migrator fails.

fix: fix misc. logging issues

---

src/controllers/accounts.js
test/accountSpec.js

Allow less flexibility when registering accounts. We can decide to relax this at any point in the future since the strict regex is only applied during registration.

feat: stricter account registration regex

---

package.json

co-body@4.x.x has a vulnerability that is fixed in co-body@5.x.x

build: updates dependency co-body to latest

---

src/lib/config.js
test/configSpec.js
test/metadataSpec.js
test/putTransferSpec.js

if the currency is for instance dollars, precision will now be nanodollars, and maximum balance will
be 10 billion dollars

perf: Change default scale,precision to 10 digits before the comma, 9 after

---

README.md
package.json

sqlite3 is needed for 'Step 3' from the readme, as well as for `npm test`.
The Docker-based instructions still referred to mysql, updated it to postgres.

readme fixes and sqlite3 devDependency

---

README.md

The env var for setting the admin user password was missing, so you couldn't do anything with the ledger from the Docker instructions.
These additions also explain how to create a user, how to inspect the database, how to connect a plugin, and add a word of warning about reliability.

docs: Add more usage info to the readme

---

src/lib/app.js
test/fulfillmentSpec.js
test/getTransferSpec.js
test/notificationSpec.js
test/rejectionSpec.js
test/transferStateSpec.js

- feat: Adds authentication to all endpoints under /transfers/*
- test: changes requests to /transfers/* to use basic auth
- test: validates that requests to /transfers/* have to be authenticated

feat: Adds authentication to all endpoints under /transfers/*

---

src/controllers/metadata.js
test/metadataSpec.js

There is currently no way to know which version a ledger is running, other than if the ledger was discovered through an ilp-kit WebFinger record. Adding this, fixes that.

feat: Announce API version in metadata

---

src/lib/db.js

Currently, when using five-bells-ledger as a dependency you may get this error:
```
[ledger] 2017-05-10T23:19:48.020Z ledger:app error error: relation "L_LU_REJECTION_REASON" does not exist
[ledger]     at Connection.parseE (/opt/workspace/interledgerjs/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/opt/workspace/interledgerjs/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/opt/workspace/interledgerjs/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:191:7)
[ledger]     at readableAddChunk (_stream_readable.js:178:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:136:10)
[ledger]     at TCP.onread (net.js:561:20) …
```

fix: use correct pg-migrator path, no matter where it is

---

.dockerignore
Dockerfile

The previous workflow of building the docker image (i.e. 1) npm install, 2) docker build ... ) only worked if the host node version is the same as the one used inside the docker container (otherwise, when starting the app inside the container, node is complaining that native dependencies were compiled for a different node version). This commit fixes this issue by running npm install during the docker build, thereby compiling all dependencies for the node version used by the container.

build: run npm install during docker build
